### ISSUE TITLE
typing: dt namespace doesn't preserve input subclass

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1229]
```python
import narwhals.stable.v1 as nw

s: nw.Series
reveal_type(s.dt.date())
```
if you run `mypy` on the file above, you get
```
note: Revealed type is "narwhals.series.Series"
```

However, it should be:
```
Revealed type is "narwhals.stable.v1.Series"
```

```
System:
    python: 3.12.6 (main, Sep  9 2024, 22:11:19) [Clang 18.1.8 ]
executable: /home/marcogorelli/polars-api-compat-dev/.venv/bin/python3
   machine: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

Python dependencies:
     narwhals: 1.9.4
       pandas: 2.2.3
       polars: 1.0.0
         cudf: 
        modin: 
      pyarrow: 15.0.0
        numpy: 1.26.4
```
