### ISSUE TITLE
[Bug]: ModuleNotFoundError for ‘grpc’ and ‘google’ when using PySpark in Marimo

### ISSUE THREAD

**Issue by khuyentran1401** [narwhals-dev/narwhals#2517]
### Describe the bug

When attempting to use PySpark within Marimo, I encounter the following error:

```bash
ModuleNotFoundError: No module named 'grpc'
```

and 

```bash
ModuleNotFoundError: No module named 'google'
```

## Steps to Reproduce

1. Open a Marimo notebook.
2. Add the following code cell:

``` python
from datetime import date
import pandas as pd
from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()
```

3. Run the cell. This leads to the following error (abbreviated):

```bash
ModuleNotFoundError: No module named 'grpc'
...
ImportError: grpcio >= 1.48.1 must be installed; however, it was not found.
...
ModuleNotFoundError: No module named 'google'
```

## Dependencies

```toml
requires-python = ">=3.11"
dependencies = [
    "narwhals==1.38.1",
    "marimo",
    "pandas==2.2.3",
    "pyarrow==20.0.0",
    "pyspark==3.5.5",
]
```

### Expected results

The code executes without errors, and Narwhals silently handles the date variable or Spark object without requiring manual installation of missing dependencies.

### Actual results

An error is raised due to missing dependencies (grpcio, google) when Narwhals tries to interpret the Spark session context or date variable.

### Please run narwhals.show_version() and enter the output below.

```shell
narwhals==1.38.1
```

### Relevant log output

```shell

```
